In [1]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.datasets import fetch_openml
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.utils import check_random_state
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
train_samples = 5000

In [3]:
# Load data from https://www.openml.org/d/554
X, y = fetch_openml('mnist_784', version=1, return_X_y=True)
random_state = check_random_state(0)
permutation = random_state.permutation(X.shape[0])
X = X[permutation]
y = y[permutation]
X = X.reshape((X.shape[0], -1))
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=train_samples, test_size=10000)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
clf = LogisticRegression(max_iter=50)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
conf_m = confusion_matrix(y_test, y_pred)
print('Confusion Matrix:', conf_m, sep='\n', end='\n\n')
report = classification_report(y_test, y_pred)
print('Classification Report:', report, sep='\n')

/home/iyoushe/.local/lib/python3.6/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


Confusion Matrix:
[[ 923    1   12    6    4   13    7    4    9    2]
 [   0 1067   11   11    1    4    2    7   20    2]
 [  16   17  785   29   20   13   21   26   25    6]
 [   4   10   34  875    3   54    3   14   26   15]
 [   6    4    6    1  875    8    9    8    9   43]
 [  16    9   15   44   18  711   12    2   35   12]
 [  12   11   19    7   17   28  939    1    5    0]
 [   2   11   11   12   26    2    2  913    7   49]
 [   8   29   25   24   15   62   13    6  785   32]
 [   7    5    1   14   36   11    1   46   14  847]]

Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.94      0.93       981
           1       0.92      0.95      0.93      1125
           2       0.85      0.82      0.84       958
           3       0.86      0.84      0.85      1038
           4       0.86      0.90      0.88       969
           5       0.78      0.81      0.80       874
           6       0.93      0.90      0.92     